version: '3.9'

services:
  web:
    image: mediumnewsbot
    container_name: mediumnewsbot
    restart: always
    volumes:
      - /mnt/vol1/mediumnewsbot:/usr/src/app/db
    environment:
      TELEGRAF_TOKEN: "my-telegram-bot-token"
      FETCHING_DURATION: 5
      SENDING_DURATION: 3
