version: '3.9'

services:
  web:
    image: lexermal/spotify-podcast-notifier-bot
    container_name: spotify-podcast-notifier-bot
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /tmp/spotify-podcast-notifier-bot:/usr/src/app/db
    environment:
      TELEGRAF_TOKEN: "my-telegram-bot-token"
      FETCHING_DURATION: 5
      SENDING_DURATION: 3
      SPOTIFY_CLIENT_ID: "my-spotify-client-id"
      SPOTIFY_CLIENT_SECRET: "my-spotify-client-secret"
      DOMAIN_URL: http://localhost:3000

