apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spotify-podcast-notifier-bot-pvc
  labels:
    {{- include "spotify-notifier-charts.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 